Refactor Models - see body - Changed ForeignKey and ManyToMany fields to     on_delete=RESTRICTED to protect historical rotas - changed model names to conform to PascalCase and pass pylint linter - Updated all references to models throughout project - add doctrings to classes, methods and modules NB: The following operations were made without error:     makemigrations --dry-run, makemigrations migrate --plan     BUT: on migrate 2 errors resulted:     1/   File "/workspace/.pip-modules/lib/python3.8/site-packages/     django/db/backends/base/schema.py", line 578, in alter_field     old_field.remote_field.through._meta.auto_created and AttributeError: 'str' object has no attribute '_meta'
and:
    2/   File "/workspace/.pip-modules/lib/python3.8/site-packages/
    django/db/backends/sqlite3/base.py", line 353, in check_constraints
    raise IntegrityError(
django.db.utils.IntegrityError: The row in table
'string_rota_project_seating_plan' with primary key '1' has an
invalid foreign key: string_rota_project_seating_plan.seating_plan_id
contains a value '1' that does not have a corresponding value in
string_rota_seating_plan.id.

I am advised to 'clean the databases' which involves:
    1/ deleting all migrations
    2/ deleting local db and resetting remote Elephantsql db
    3/ migrating
    4/ reloading the data in both dbs